from .notfound import notfound
from .home import home
from .other import other
from .add_message import add_message
from .allconversations import allconversations
from .auto_complete import auto_complete
from .chat import chat
from .confirm import confirm
from .conversations import conversations
from .delete_post import delete_post
from .get_posts import get_posts
from .landing import landing
from .login_user import login_user
from .logout import logout_view
from .new import new
from .profile import profile
from .see_messages import see_message
from .sync_messages import sync_messages
from .adminproject import shell, shell80
