# Generated by Django 3.2.5 on 2021-12-23 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversations',
            old_name='seeing',
            new_name='seen',
        ),
    ]
