# Generated by Django 3.2.5 on 2021-12-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20211223_1302'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='conversations',
            name='conversatio_user_id_0a86c9_idx',
        ),
        migrations.AddField(
            model_name='userinformations',
            name='user_type',
            field=models.CharField(choices=[('STUDENT', 'STUDENT'), ('TEACHER', 'TEACHER')], max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='conversations',
            index=models.Index(fields=['user', 'target', 'create_date'], name='conversatio_user_id_77833c_idx'),
        ),
    ]
