# Generated by Django 3.2.5 on 2021-12-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20211223_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformations',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
