# Generated by Django 3.2.5 on 2021-12-23 15:44

import chat.models.user_informations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_userinformations_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformations',
            name='user_type',
            field=models.CharField(choices=[('STUDENT', 'STUDENT'), ('TEACHER', 'TEACHER')], default=chat.models.user_informations.UserInformations.UserType['STUDENT'], max_length=255, null=True),
        ),
    ]
