# Generated by Django 3.2.5 on 2021-12-28 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_userinformations_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversations',
            name='block',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinformations',
            name='is_ban',
            field=models.BooleanField(default=False),
        ),
    ]
