# Generated by Django 3.2.5 on 2021-12-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20211228_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformations',
            name='user_type',
            field=models.CharField(choices=[('STUDENT', 'STUDENT'), ('TEACHER', 'TEACHER')], default='STUDENT', max_length=255, null=True),
        ),
    ]
